apiVersion: v1
kind: Secret
metadata:
  name: ${APP_NAME}-config
  namespace: ${NAMESPACE}
type: Opaque
stringData:
  deployment.toml: |-
    icpVersion = "${ICP_VERSION}"
    serverHost = "0.0.0.0"
    serverPort = 9446
    runtimeListenerPort = 9445
    defaultOpensearchAdaptorPort = 9449
    publicBaseUrl = "https://${INGRESS_URL}"
    sslEnabled = true
    keystorePassword = "${KEYSTORE_PASSWORD_TOML}"
    truststorePassword = "${TRUSTSTORE_PASSWORD_TOML}"
    logLevel = "${LOG_LEVEL}"
    frontendJwtHMACSecret = "${FRONTEND_JWT_HMAC_SECRET_TOML}"
    userServiceJwtHMACSecret = "${USER_SERVICE_JWT_HMAC_SECRET_TOML}"
    observabilityJwtHMACSecret = "${OBSERVABILITY_JWT_HMAC_SECRET_TOML}"
    credentialsDbType = "postgresql"
    credentialsDbHost = "${CREDENTIALS_DB_HOST_TOML}"
    credentialsDbPort = ${CREDENTIALS_DB_PORT}
    credentialsDbName = "${CREDENTIALS_DB_NAME_TOML}"
    credentialsDbUser = "${CREDENTIALS_DB_USERNAME_TOML}"
    credentialsDbPassword = "${CREDENTIALS_DB_PASSWORD_TOML}"
    credentialsDbUseTLS = ${DB_USE_TLS}
    opensearchUrl = "${OPENSEARCH_URL_TOML}"
    opensearchUsername = "${OPENSEARCH_USERNAME_TOML}"
    opensearchPassword = "${OPENSEARCH_PASSWORD_TOML}"

    [icp_server.storage]
    dbType = "postgresql"
    dbHost = "${DB_HOST_TOML}"
    dbPort = ${DB_PORT}
    dbName = "${DB_NAME_TOML}"
    dbUser = "${DB_USERNAME_TOML}"
    dbPassword = "${DB_PASSWORD_TOML}"
    dbUseTLS = ${DB_USE_TLS}
    maxOpenConnections = 50
    minIdleConnections = 5
    maxConnectionLifeTime = 1800.0
    deploymentType = "K8S"
