k8s-hml:
  stage: deploy
  image:
    name: ${IMG_DOCKER_KUBECTL}
    entrypoint: [""]
  tags:
    - int-lnx-run01
  variables:
    CONTEXT: gitlab-ci-integration-hml
    TAG: $CI_COMMIT_TAG
    KUBECONFIG_CONTENT_BASE64: ${KUBECONFIG_BASE64_INTEGRATION_HML}
    INGRESS_URL: ${ICP_INGRESS_URL_HML}
    VAR_REPLICAS: 1
    VAR_TERMINATION_GRACE_PERIOD_SECONDS: 30
    VAR_CONTAINERS_RESOURCES_REQUESTS_CPU: 100m
    VAR_CONTAINERS_RESOURCES_REQUESTS_MEMORY: 512Mi
    VAR_CONTAINERS_RESOURCES_LIMITS_CPU: 300m
    VAR_CONTAINERS_RESOURCES_LIMITS_MEMORY: 768Mi
    VAR_MAX_REPLICAS: 1
    VAR_MIN_REPLICAS: 1
    DB_HOST: ${ICP_DB_HOST_HML}
    DB_PORT: ${ICP_DB_PORT_HML}
    DB_NAME: ${ICP_DB_NAME_HML}
    DB_USERNAME: ${ICP_DB_USERNAME_HML}
    DB_PASSWORD: ${ICP_DB_PASSWORD_HML}
    DB_USE_TLS: "false"
    ICP_ADMIN_PASSWORD: ${ICP_ADMIN_PASSWORD_HML}
    FRONTEND_JWT_HMAC_SECRET: ${ICP_FRONTEND_JWT_HMAC_SECRET_HML}
    USER_SERVICE_JWT_HMAC_SECRET: ${ICP_USER_SERVICE_JWT_HMAC_SECRET_HML}
    OBSERVABILITY_JWT_HMAC_SECRET: ${ICP_OBSERVABILITY_JWT_HMAC_SECRET_HML}
    OPENSEARCH_URL: ${ICP_OPENSEARCH_URL_HML}
    OPENSEARCH_USERNAME: ${ICP_OPENSEARCH_USERNAME_HML}
    OPENSEARCH_PASSWORD: ${ICP_OPENSEARCH_PASSWORD_HML}
    LOG_LEVEL: INFO
  environment:
    name: k8s-hml
    url: https://${INGRESS_URL}
  extends:
    - .script-deploy
    - .rules-deploy-hml
