docker:
  stage: docker
  image: ${IMG_DOCKER}
  services:
    - ${IMG_DOCKER_DIND}
  variables:
    REGISTRY_URL: ${NEXUS_REGISTRY_URL}
    REGISTRY_USER: ${NEXUS_REGISTRY_USER}
    REGISTRY_PASS: ${NEXUS_REGISTRY_PASSWORD}
  needs:
    - job: build
      artifacts: true
  before_script:
    - |
      if [ -n "${CI_COMMIT_TAG:-}" ]; then
        export TAG=$CI_COMMIT_TAG
      else
        export TAG=$CI_COMMIT_SHA
      fi
  extends:
    - .script-docker
    - .rules-docker
